### ISSUE TITLE
Standortmapping für die Standorte "Temporäre Erwerbungssignaturen"

### ISSUE THREAD

**Issue by florianruckelshausen** [florianruckelshausen/cbs2folio-transformations#8]
In FOLIO sind für UB und die Zweigbibliotheken jeweils Standorte für "Temporäre Erwerbungssignaturen" angelegt. Bisher nutzen wir das nur an der UB und triggern auf die Signaturen "vergriffen", "storniert" und "bestellt". An den Zweigbibliotheken werden die Standorte bisher über die Regeln nicht befüllt.

Die drei Regeln können wir auch auf die Zweigbibliotheken ausdehnen. Das bekomme ich hin, da müssen wir die bestehenden Regeln nur adaptieren.

Meine Idee wäre aber, dass wir auch nach dem Ausleihindikator a schauen und diesen als weiteres Kriterium heranziehen, um auf diese Standorte zu mappen. @michaelfreiberg : das müsstest du machen. Da bin ich mir unsicher.

**Comment by florianruckelshausen** [comment]
Das Übertragen der drei Signaturregeln habe ich eingefügt.

**Comment by michaelfreiberg** [comment]
Mit dem Commit f04f6a6 habe ich eine when-Klausel eingefügt, die im Fall eines Ausleihindikators a die Erwerbungssignaturenstandorte je nach Abteilungscode zuweist. Diese Fälle habe ich auch alle schon getestet.

```xml
<xsl:when test="$loan-type = 'a'">
  <xsl:choose>
    <xsl:when test="$abt = '000'">ILN204/CG/UB/Erwerbungssignatur</xsl:when>
    <xsl:when test="$abt = '002'">ILN204/CG/ZNL/Erwerbungssignatur</xsl:when>            
    <xsl:when test="$abt = '005'">ILN204/CG/ZHB/Erwerbungssignatur</xsl:when>
    <xsl:when test="$abt = '009'">ILN204/CG/ZP2/Erwerbungssignatur</xsl:when>
    <xsl:when test="$abt = '010'">ILN204/CG/ZRW/Erwerbungssignatur</xsl:when>
    <xsl:when test="$abt = '020'">ILN204/CG/ZRW/Erwerbungssignatur</xsl:when>
    <xsl:when test="$abt = '030'">ILN204/CG/ZP2/Erwerbungssignatur</xsl:when>            
  </xsl:choose>
</xsl:when>
```
Es gibt kein `xsl:otherwise` für alle anderen Fälle, was bedeutet, dass alle anderen Abteilungscodes ihre jeweilige Standortbehandlung erfahren. Oder wäre es sinnvoll, sie dem Standort **ILN204/CG/UB/Erwerbungssignatur** oder einem Erwerbungssammler zuzuweisen?

Wichtig: in der UB gibt es bereits x - Signaturen: `<range from="x 0" to="x 999999" location="ILN204/CG/UB/UBMagKeller"/>`. Mit dem Präfix `<prefix location="ILN204/CG/UB/Erwerbungssignatur">x</prefix>` würden sie als Erwerbungssignaturen behandelt werden. Mögliche Lösung: die x-Erwerbungssignaturen hinter die x 0 - x 999999-Range setzen.

In der Fallbehandlung der aktuellen Fassung haben die Erwerbungssignaturen Vorrang vor den HAPs:
```
<xsl:when test="$loan-type = 'a'">
[...]
</xsl:when>
<xsl:when test="$dummy or $article-in-volume">ILN204/CG/Aufsatz/Aufsatzkatalogisate</xsl:when>
<xsl:when test="$hap">
[...]
```
In der Anzeige wirkt es sich so aus, dass nicht der HAP-Standort, sondern der Erwerbungssignaturen-Standort angezeigt wird, z.B. PPN 521908272.

Ich habe noch eine kleine (unwichtige) Abweichung festgestellt. Im Fall der UB ist das Label "Temporäre Erwerbungssignaturen", in allen anderen Fällen nur "Erwerbungssignaturen".

Außerdem gibt es in der Abteilung 030 noch keine x-Erwerbungssignaturen.

**Comment by michaelfreiberg** [comment]
Die Commits c37a813ff69811a144ed3bcfe992acb25ec410e2 (Unterscheidung x-Signaturen) und fc14d2478ae147b0036852ea5ddceb813b2ff151 (Erwerbungssignatur x für ZP2) enthalten die Änderungen.
